const contractAddress = "0xe68738Db4e7Bb31d7C3633D6Df40FB9223a1Ee16"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "This Is Crack Rabbit Collective";
const welcome_h2 = "Connect your wallet 4 crack";
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "These Crack Rabbits ain't easy to get ahold of. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You ain't whitelisted for no pre-sale";
const p_presale_mint_whitelisted = "You're on da pre-sale whitelist!";
const p_presale_mint_already_minted = "Take it easy you've already got your whitelist mint";
const p_public_mint = "No whitelist needed. Public minting is now open!";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Crack Rabbit";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Crackmmunity";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. try again.";
